import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
    // Deletes ALL existing entries
    await knex('districts').del();

    // Inserts seed entries for districts
    await knex('districts').insert([
        {
            name: 'Andijon tumani',
            description: 'Andijon viloyatidagi asosiy tumanlardan biri',
            region_id: 50,
        },
        { name: 'Asaka tumani', description: 'Andijon viloyatidagi sanoat markazi', region_id: 50 },
        {
            name: 'Baliqchi tumani',
            description: "Baliqchilik va qishloq xo'jaligi bilan mashhur",
            region_id: 50,
        },
        { name: "Bo'z tumani", description: 'Qadimiy tarixga ega hudud', region_id: 50 },
        {
            name: 'Izboskan tumani',
            description: "Farg'ona vodiysining sharqiy qismi",
            region_id: 50,
        },
        {
            name: 'Jalolquduq tumani',
            description: "Qishloq xo'jaligi uchun mo'ljallangan hudud",
            region_id: 50,
        },
        { name: 'Qorasuv tumani', description: 'Tabiiy resurslari boy hudud', region_id: 50 },
        { name: 'Marhamat tumani', description: 'Tarixiy va madaniy obidalarga boy', region_id: 50 },
        { name: "Oltinko'l tumani", description: "Suv xo'jaligi bilan mashhur", region_id: 50 },
        { name: 'Paxtaobod tumani', description: 'Paxta yetishtirish markazi', region_id: 50 },
        { name: 'Shahrihon tumani', description: 'Savdo va sanoat markazi', region_id: 50 },
        { name: "Ulug'nor tumani", description: "Yosh aholisi ko'p hudud", region_id: 50 },
        { name: "Xo'jaobod tumani", description: 'Chegaraviy hudud', region_id: 50 },
        { name: 'Buxoro tumani', description: 'Buxoro shahriga yaqin tuman', region_id: 51 },
        { name: 'G‘ijduvon tumani', description: 'Hunarmandchilik va savdo markazi', region_id: 51 },
        { name: 'Jondor tumani', description: 'Qadimiy shaharlar bilan mashhur', region_id: 51 },
        { name: 'Kogon tumani', description: "Sanoat va qishloq xo'jaligi hududi", region_id: 51 },
        {
            name: 'Olot tumani',
            description: 'Tabiiy manzaralari bilan ajralib turadi',
            region_id: 51,
        },
        { name: 'Peshku tumani', description: "Kichik qishloq xo'jaligi hududi", region_id: 51 },
        { name: 'Qorako‘l tumani', description: 'Qadimiy madaniyat markazi', region_id: 51 },
        {
            name: 'Qorovulbozor tumani',
            description: "Dehqonchilik bilan shug'ullaniladi",
            region_id: 51,
        },
        { name: 'Romitan tumani', description: 'Tarixiy obidalarga ega', region_id: 51 },
        {
            name: 'Shofirkon tumani',
            description: "Qishloq xo'jaligi va chorvachilik",
            region_id: 51,
        },
        { name: 'Vobkent tumani', description: "Suv ta'minoti bilan mashhur", region_id: 51 },
        { name: 'Jizzax tumani', description: 'Jizzax shahriga yaqin tuman', region_id: 52 },
        { name: 'Arnasoy tumani', description: "Cho'l hududida joylashgan", region_id: 52 },
        { name: 'Baxmal tumani', description: "Tog'li hudud va tabiiy go'zalliklar", region_id: 52 },
        { name: 'Do‘stlik tumani', description: 'Yangi rivojlanayotgan hudud', region_id: 52 },
        { name: 'Forish tumani', description: 'Tabiiy resurslari boy', region_id: 52 },
        { name: 'G‘allaorol tumani', description: 'Don yetishtirish markazi', region_id: 52 },
        {
            name: 'Mirzacho‘l tumani',
            description: "Cho'l hududida qishloq xo'jaligi",
            region_id: 52,
        },
        {
            name: 'Paxtakor tumani',
            description: "Paxta yetishtirish uchun mo'ljallangan",
            region_id: 52,
        },
        { name: 'Yangiobod tumani', description: "Tog'li va tabiiy manzarali hudud", region_id: 52 },
        { name: 'Zarbdor tumani', description: "Sanoat va qishloq xo'jaligi", region_id: 52 },
        {
            name: 'Qamashi tumani',
            description: 'Qashqadaryo viloyatining janubiy qismi',
            region_id: 53,
        },
        { name: 'Kitob tumani', description: 'Tarixiy shaharlar bilan mashhur', region_id: 53 },
        { name: 'Koson tumani', description: 'Qadimiy madaniyat markazi', region_id: 53 },
        { name: 'Kuktepa tumani', description: 'Yangi rivojlanayotgan hudud', region_id: 53 },
        { name: 'Mirishkor tumani', description: "Qishloq xo'jaligi hududi", region_id: 53 },
        { name: 'Muborak tumani', description: 'Neft industriyasi markazi', region_id: 53 },
        { name: 'Nishon tumani', description: 'Tarixiy va madaniy boyliklar', region_id: 53 },
        { name: 'Shahrisabz tumani', description: "Amir Temurning tug'ilgan joyi", region_id: 53 },
        {
            name: 'Chiroqchi tumani',
            description: "Tog'li va qishloq xo'jaligi hududi",
            region_id: 53,
        },
        { name: 'Yakkabog‘ tumani', description: 'Tabiiy manzarali hudud', region_id: 53 },
        { name: 'Navbahor tumani', description: 'Navoiy viloyatidagi yangi tuman', region_id: 54 },
        { name: 'Konimex tumani', description: 'Kon sanoati bilan mashhur', region_id: 54 },
        {
            name: 'Nurata tumani',
            description: "Qadimiy shahar va tabiiy go'zalliklar",
            region_id: 54,
        },
        { name: 'Qiziltepa tumani', description: "Cho'l hududida joylashgan", region_id: 54 },
        { name: 'Tomdi tumani', description: "Qishloq xo'jaligi va chorvachilik", region_id: 54 },
        { name: 'Uchquduq tumani', description: 'Tabiiy resurslari boy hudud', region_id: 54 },
        { name: 'Xatirchi tumani', description: "Sanoat va qishloq xo'jaligi", region_id: 54 },
        {
            name: 'Yangiro‘l tumani',
            description: 'Namangan viloyatidagi yirik tuman',
            region_id: 55,
        },
        { name: 'Chortoq tumani', description: 'Tabiiy manzarali hudud', region_id: 55 },
        { name: 'Kosonsoy tumani', description: "Qishloq xo'jaligi markazi", region_id: 55 },
        { name: 'Mingbuloq tumani', description: 'Yangi rivojlanayotgan hudud', region_id: 55 },
        { name: 'Namangan tumani', description: 'Namangan shahriga yaqin tuman', region_id: 55 },
        { name: 'Norin tumani', description: "Tog'li hudud va qishloq xo'jaligi", region_id: 55 },
        { name: 'Pop tumani', description: 'Savdo va sanoat markazi', region_id: 55 },
        { name: 'Turakurgan tumani', description: 'Chegaraviy hudud', region_id: 55 },
        { name: 'Uchqorg‘on tumani', description: 'Qadimiy tarixga ega', region_id: 55 },
        {
            name: 'Yangiqo‘rg‘on tumani',
            description: "Qishloq xo'jaligi bilan shug'ullaniladi",
            region_id: 55,
        },
        { name: 'Bafqulov tumani', description: 'Navoiy viloyatidagi yangi tuman', region_id: 56 },
        { name: 'Bog‘dod tumani', description: "Qishloq xo'jaligi hududi", region_id: 56 },
        { name: 'Bulung‘ur tumani', description: 'Tarixiy obidalarga ega', region_id: 56 },
        { name: 'Ishtixon tumani', description: 'Qadimiy shahar va savdo markazi', region_id: 56 },
        { name: 'Jomboy tumani', description: "Qishloq xo'jaligi va chorvachilik", region_id: 56 },
        { name: 'Kattakurgan tumani', description: "Sanoat va qishloq xo'jaligi", region_id: 56 },
        { name: 'Narpay tumani', description: 'Tabiiy manzarali hudud', region_id: 56 },
        { name: 'Oqdaryo tumani', description: "Suv xo'jaligi bilan mashhur", region_id: 56 },
        { name: 'Payariq tumani', description: "Qishloq xo'jaligi markazi", region_id: 56 },
        { name: 'Pastdarg‘om tumani', description: 'Yangi rivojlanayotgan hudud', region_id: 56 },
        {
            name: 'Qamashi tumani',
            description: 'Qashqadaryo viloyatining janubiy qismi',
            region_id: 56,
        },
        { name: 'Samarqand tumani', description: 'Samarqand shahriga yaqin tuman', region_id: 56 },
        { name: 'Tayloq tumani', description: "Tog'li hudud va qishloq xo'jaligi", region_id: 56 },
        { name: 'Urgut tumani', description: 'Qadimiy madaniyat markazi', region_id: 56 },
        {
            name: 'Sirdaryo tumani',
            description: 'Sirdaryo viloyatidagi asosiy tuman',
            region_id: 57,
        },
        {
            name: 'Boyovut tumani',
            description: "Qishloq xo'jaligi bilan shug'ullaniladi",
            region_id: 57,
        },
        { name: 'Guliston tumani', description: 'Guliston shahriga yaqin tuman', region_id: 57 },
        { name: 'Mirzaobod tumani', description: "Suv ta'minoti bilan mashhur", region_id: 57 },
        { name: 'Oqqo‘rg‘on tumani', description: 'Yangi rivojlanayotgan hudud', region_id: 57 },
        { name: 'Sardoba tumani', description: 'Suv ombori bilan mashhur', region_id: 57 },
        { name: 'Sayxunobod tumani', description: "Qishloq xo'jaligi hududi", region_id: 57 },
        { name: 'Shirin tumani', description: 'Tabiiy manzarali hudud', region_id: 57 },
        { name: 'Yangiyer tumani', description: "Sanoat va qishloq xo'jaligi", region_id: 57 },
        {
            name: 'Angren tumani',
            description: 'Toshkent viloyatidagi sanoat markazi',
            region_id: 58,
        },
        { name: 'Bekabod tumani', description: "Sanoat va qishloq xo'jaligi hududi", region_id: 58 },
        { name: 'Bo‘ka tumani', description: 'Qadimiy tarixga ega hudud', region_id: 58 },
        {
            name: 'Chinoz tumani',
            description: "Qishloq xo'jaligi bilan shug'ullaniladi",
            region_id: 58,
        },
        { name: 'Qibray tumani', description: 'Toshkent shahriga yaqin tuman', region_id: 58 },
        { name: 'Ohangaron tumani', description: 'Sanoat va tabiiy resurslar', region_id: 58 },
        { name: 'Oqqo‘rg‘on tumani', description: 'Yangi rivojlanayotgan hudud', region_id: 58 },
        { name: 'Parkent tumani', description: 'Tabiiy manzarali hudud', region_id: 58 },
        { name: 'Piskent tumani', description: "Qishloq xo'jaligi markazi", region_id: 58 },
        { name: 'Quyichirchiq tumani', description: "Suv xo'jaligi bilan mashhur", region_id: 58 },
        { name: 'Toshkent tumani', description: 'Toshkent shahriga yaqin tuman', region_id: 58 },
        {
            name: 'O‘rtachirchiq tumani',
            description: "Qishloq xo'jaligi va chorvachilik",
            region_id: 58,
        },
        { name: 'Yangiyo‘l tumani', description: 'Sanoat va savdo markazi', region_id: 58 },
        { name: 'Zangiota tumani', description: 'Yangi rivojlanayotgan hudud', region_id: 58 },
        { name: 'Farg‘ona tumani', description: "Farg'ona shahriga yaqin tuman", region_id: 59 },
        { name: 'Beshariq tumani', description: "Qishloq xo'jaligi bilan mashhur", region_id: 59 },
        { name: 'Dang‘ara tumani', description: 'Tabiiy resurslar boy hudud', region_id: 59 },
        { name: 'Furqat tumani', description: 'Qadimiy tarixga ega', region_id: 59 },
        { name: 'Qo‘qon tumani', description: "Tarixiy shahar bilan bog'liq", region_id: 59 },
        { name: 'Marg‘ilon tumani', description: 'Ipak industriyasi markazi', region_id: 59 },
        { name: 'O‘zbekiston tumani', description: 'Yangi rivojlanayotgan hudud', region_id: 59 },
        { name: 'Rishton tumani', description: 'Keramika sanoati bilan mashhur', region_id: 59 },
        { name: 'Sox tumani', description: 'Chegaraviy hudud', region_id: 59 },
        { name: 'Toshloq tumani', description: "Qishloq xo'jaligi hududi", region_id: 59 },
        { name: 'Uchko‘prik tumani', description: "Suv ta'minoti bilan mashhur", region_id: 59 },
        { name: 'Yozyovon tumani', description: 'Qadimiy madaniyat markazi', region_id: 59 },
        {
            name: 'Buloqboshi tumani',
            description: 'Surxondaryo viloyatidagi yangi tuman',
            region_id: 60,
        },
        { name: 'Boysun tumani', description: "Tog'li hudud va qadimiy madaniyat", region_id: 60 },
        { name: 'Denov tumani', description: "Qishloq xo'jaligi markazi", region_id: 60 },
        { name: 'Jarqo‘rg‘on tumani', description: 'Chegaraviy hudud', region_id: 60 },
        { name: 'Qiziriq tumani', description: 'Yangi rivojlanayotgan hudud', region_id: 60 },
        { name: 'Qumqorg‘on tumani', description: "Sanoat va qishloq xo'jaligi", region_id: 60 },
        { name: 'Muzrabot tumani', description: 'Tabiiy manzarali hudud', region_id: 60 },
        {
            name: 'Oltinsoy tumani',
            description: "Qishloq xo'jaligi bilan shug'ullaniladi",
            region_id: 60,
        },
        { name: 'Sariosiyo tumani', description: 'Tarixiy obidalarga ega', region_id: 60 },
        { name: 'Sherobod tumani', description: "Suv xo'jaligi bilan mashhur", region_id: 60 },
        { name: 'Sho‘rchi tumani', description: 'Qadimiy shaharlar bilan mashhur', region_id: 60 },
        { name: 'Termiz tumani', description: 'Termiz shahriga yaqin tuman', region_id: 60 },
        { name: 'Uzun tumani', description: 'Yangi rivojlanayotgan hudud', region_id: 60 },
        {
            name: 'Xonobod tumani',
            description: 'Xorazm viloyatidagi sanoat markazi',
            region_id: 61,
        },
        { name: 'Bog‘ot tumani', description: "Qishloq xo'jaligi hududi", region_id: 61 },
        { name: 'Gurlan tumani', description: 'Tarixiy shaharlar bilan mashhur', region_id: 61 },
        { name: 'Qoshkopa tumani', description: "Suv ta'minoti bilan mashhur", region_id: 61 },
        { name: 'Shavot tumani', description: 'Qadimiy madaniyat markazi', region_id: 61 },
        { name: 'Urganch tumani', description: 'Urganch shahriga yaqin tuman', region_id: 61 },
        {
            name: 'Xazorasp tumani',
            description: "Qishloq xo'jaligi bilan shug'ullaniladi",
            region_id: 61,
        },
        { name: 'Yangibozor tumani', description: 'Yangi rivojlanayotgan hudud', region_id: 61 },
        { name: 'Kegeyli tumani', description: "Qoraqalpog'istonda joylashgan", region_id: 62 },
        { name: 'Mo‘ynoq tumani', description: 'Aral dengizi yaqinidagi hudud', region_id: 62 },
        { name: 'Nukus tumani', description: 'Nukus shahriga yaqin tuman', region_id: 62 },
        { name: 'Qanliko‘l tumani', description: "Qishloq xo'jaligi hududi", region_id: 62 },
        { name: 'Qo‘ng‘irot tumani', description: 'Tabiiy resurslar boy', region_id: 62 },
        { name: 'Shumanay tumani', description: 'Qadimiy tarixga ega', region_id: 62 },
        { name: 'Taxiatosh tumani', description: 'Yangi tashkil etilgan tuman', region_id: 62 },
        { name: 'Turtkul tumani', description: "Sanoat va qishloq xo'jaligi", region_id: 62 },
        { name: 'Xo‘jayli tumani', description: 'Chegaraviy hudud', region_id: 62 },
        { name: 'Chimboy tumani', description: "Qishloq xo'jaligi bilan mashhur", region_id: 62 },
        { name: 'Ellikqala tumani', description: 'Tabiiy manzarali hudud', region_id: 62 },
        { name: 'Beruniy tumani', description: 'Tarixiy obidalarga ega', region_id: 62 },
    ]);
}
